// Package manifest provides functionality for writing boilerplate generation manifests.
package manifest

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/invopop/jsonschema"
	"gopkg.in/yaml.v2"

	"github.com/gruntwork-io/boilerplate/version"
)

const DefaultManifestFilename = "boilerplate-manifest.yaml"
const SchemaURL = "https://boilerplate.gruntwork.io/schemas/manifest/v1/schema.json"
const SchemaVersion = SchemaURL
const defaultFilePerm = 0o644

// ManifestDependency represents a dependency that was processed during a boilerplate run.
type ManifestDependency struct {
	Variables            map[string]any  `json:"Variables" yaml:"Variables"`
	Name                 string          `json:"Name" yaml:"Name" jsonschema:"required"`
	TemplateURL          string          `json:"TemplateURL" yaml:"TemplateURL" jsonschema:"required"`
	OutputFolder         string          `json:"OutputFolder" yaml:"OutputFolder" jsonschema:"required"`
	Skip                 string          `json:"Skip" yaml:"Skip"`
	ForEachReference     string          `json:"ForEachReference" yaml:"ForEachReference"`
	Files                []GeneratedFile `json:"Files" yaml:"Files"`
	VarFiles             []string        `json:"VarFiles" yaml:"VarFiles"`
	ForEach              []string        `json:"ForEach" yaml:"ForEach"`
	DontInheritVariables bool            `json:"DontInheritVariables" yaml:"DontInheritVariables"`
}

// Manifest represents the output manifest for a single boilerplate generation run.
type Manifest struct {
	Variables          map[string]any       `json:"Variables" yaml:"Variables" jsonschema:"required"`
	SchemaVersion      string               `json:"SchemaVersion" yaml:"SchemaVersion" jsonschema:"required"`
	Timestamp          string               `json:"Timestamp" yaml:"Timestamp" jsonschema:"required"`
	TemplateURL        string               `json:"TemplateURL" yaml:"TemplateURL" jsonschema:"required"`
	BoilerplateVersion string               `json:"BoilerplateVersion" yaml:"BoilerplateVersion" jsonschema:"required"`
	SourceChecksum     string               `json:"SourceChecksum" yaml:"SourceChecksum" jsonschema:"required"`
	OutputDir          string               `json:"OutputDir" yaml:"OutputDir" jsonschema:"required"`
	Dependencies       []ManifestDependency `json:"Dependencies" yaml:"Dependencies" jsonschema:"required"`
	Files              []GeneratedFile      `json:"Files" yaml:"Files" jsonschema:"required"`
}

// GeneratedFile represents a file that was generated by boilerplate.
type GeneratedFile struct {
	Path     string `json:"Path" yaml:"Path" jsonschema:"required"`
	Checksum string `json:"Checksum" yaml:"Checksum" jsonschema:"required"`
}

// NewManifest creates a new Manifest with the current timestamp and boilerplate version.
func NewManifest(templateURL, outputDir, sourceChecksum string, files []GeneratedFile, variables map[string]any, dependencies []ManifestDependency) *Manifest {
	return &Manifest{
		SchemaVersion:      SchemaVersion,
		Timestamp:          time.Now().UTC().Format(time.RFC3339),
		TemplateURL:        templateURL,
		BoilerplateVersion: version.GetVersion(),
		SourceChecksum:     sourceChecksum,
		OutputDir:          outputDir,
		Files:              files,
		Variables:          variables,
		Dependencies:       dependencies,
	}
}

// WriteManifest writes the manifest to the given path. The format (JSON or YAML)
// is auto-detected from the file extension: .json produces JSON, everything else
// produces YAML. If an existing file at manifestPath is corrupted (cannot be
// parsed), an error is returned.
func WriteManifest(manifestPath string, m *Manifest) error {
	// If the file already exists, verify it is not corrupted by attempting to parse it.
	if data, err := os.ReadFile(manifestPath); err == nil {
		if parseErr := parseManifestBytes(manifestPath, data); parseErr != nil {
			return fmt.Errorf("existing manifest file %s is corrupted: %w", manifestPath, parseErr)
		}
	}

	var (
		data []byte
		err  error
	)

	if isJSONExtension(manifestPath) {
		data, err = json.MarshalIndent(m, "", "  ")
	} else {
		data, err = yaml.Marshal(m)
	}

	if err != nil {
		return err
	}

	return os.WriteFile(manifestPath, data, defaultFilePerm)
}

// parseManifestBytes tries to unmarshal data as JSON or YAML (based on extension)
// and returns an error if it fails.
func parseManifestBytes(manifestPath string, data []byte) error {
	var m Manifest

	if isJSONExtension(manifestPath) {
		return json.Unmarshal(data, &m)
	}

	return yaml.Unmarshal(data, &m)
}

// isJSONExtension returns true if the file extension indicates JSON format.
func isJSONExtension(path string) bool {
	return strings.ToLower(filepath.Ext(path)) == ".json"
}

// SHA256File computes the SHA256 checksum of a file and returns it as "sha256:<hex>".
func SHA256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}

	return "sha256:" + hex.EncodeToString(h.Sum(nil)), nil
}

// GenerateSchema returns a JSON Schema for the Manifest type.
func GenerateSchema() *jsonschema.Schema {
	reflector := jsonschema.Reflector{
		DoNotReference: true,
	}
	schema := reflector.Reflect(&Manifest{})
	schema.ID = jsonschema.ID(SchemaURL)
	schema.Title = "Boilerplate Manifest Schema"
	schema.Description = "Schema for boilerplate generation manifest"

	return schema
}
