// Package manifest provides functionality for writing boilerplate generation manifests.
package manifest

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/invopop/jsonschema"
	"gopkg.in/yaml.v3"

	"github.com/gruntwork-io/boilerplate/version"
)

const DefaultManifestFilename = "boilerplate-manifest.yaml"
const SchemaURL = "https://boilerplate.gruntwork.io/schemas/manifest/v1/schema.json"
const SchemaVersion = SchemaURL
const defaultFilePerm = 0o644

// ManifestDependency represents a dependency that was processed during a boilerplate run.
type ManifestDependency struct {
	Variables            map[string]any  `json:"Variables,omitempty" yaml:"Variables,omitempty"`
	Name                 string          `json:"Name" yaml:"Name" jsonschema:"required"`
	TemplateURL          string          `json:"TemplateURL" yaml:"TemplateURL" jsonschema:"required"`
	OutputFolder         string          `json:"OutputFolder" yaml:"OutputFolder" jsonschema:"required"`
	SourceChecksum       string          `json:"SourceChecksum,omitempty" yaml:"SourceChecksum,omitempty"`
	Skip                 string          `json:"Skip,omitempty" yaml:"Skip,omitempty"`
	ForEachReference     string          `json:"ForEachReference,omitempty" yaml:"ForEachReference,omitempty"`
	Files                []GeneratedFile `json:"Files,omitempty" yaml:"Files,omitempty"`
	VarFiles             []string        `json:"VarFiles,omitempty" yaml:"VarFiles,omitempty"`
	ForEach              []string        `json:"ForEach,omitempty" yaml:"ForEach,omitempty"`
	DontInheritVariables bool            `json:"DontInheritVariables,omitempty" yaml:"DontInheritVariables,omitempty"`
}

// Manifest represents the output manifest for a single boilerplate generation run.
type Manifest struct {
	Variables          map[string]any       `json:"Variables" yaml:"Variables" jsonschema:"required" jsonschema_description:"User-defined template variables used during generation"`
	SchemaVersion      string               `json:"SchemaVersion" yaml:"SchemaVersion" jsonschema:"required"`
	Timestamp          string               `json:"Timestamp" yaml:"Timestamp" jsonschema:"required"`
	TemplateURL        string               `json:"TemplateURL" yaml:"TemplateURL" jsonschema:"required"`
	BoilerplateVersion string               `json:"BoilerplateVersion" yaml:"BoilerplateVersion" jsonschema:"required"`
	SourceChecksum     string               `json:"SourceChecksum" yaml:"SourceChecksum" jsonschema:"required,pattern=^(git-sha1|git-sha256|sha256):.+$" jsonschema_description:"Checksum of the template source. For git sources: git-sha1:{commit} or git-sha256:{commit}. For local sources: sha256:{hex}."`
	OutputDir          string               `json:"OutputDir" yaml:"OutputDir" jsonschema:"required"`
	Dependencies       []ManifestDependency `json:"Dependencies" yaml:"Dependencies" jsonschema:"required"`
	Files              []GeneratedFile      `json:"Files" yaml:"Files" jsonschema:"required"`
}

// GeneratedFile represents a file that was generated by boilerplate.
type GeneratedFile struct {
	Path     string `json:"Path" yaml:"Path" jsonschema:"required"`
	Checksum string `json:"Checksum" yaml:"Checksum" jsonschema:"required,pattern=^[a-z0-9]+:.+$" jsonschema_description:"Hash of the file contents, prefixed with the algorithm (e.g. sha256:abcdef…)"`
}

// NewManifest creates a new Manifest with the current timestamp and boilerplate version.
func NewManifest(templateURL, outputDir, sourceChecksum string, files []GeneratedFile, variables map[string]any, dependencies []ManifestDependency) *Manifest {
	return &Manifest{
		SchemaVersion:      SchemaVersion,
		Timestamp:          time.Now().UTC().Format(time.RFC3339),
		TemplateURL:        templateURL,
		BoilerplateVersion: version.GetVersion(),
		SourceChecksum:     sourceChecksum,
		OutputDir:          outputDir,
		Files:              files,
		Variables:          variables,
		Dependencies:       dependencies,
	}
}

// WriteManifest writes the manifest to the given path. The format (JSON or YAML)
// is auto-detected from the file extension: .json produces JSON, everything else
// produces YAML.
func WriteManifest(manifestPath string, m *Manifest) error {
	var (
		data []byte
		err  error
	)

	if isJSONExtension(manifestPath) {
		data, err = json.MarshalIndent(m, "", "  ")
	} else {
		data, err = yaml.Marshal(m)
	}

	if err != nil {
		return err
	}

	return os.WriteFile(manifestPath, data, defaultFilePerm)
}

// isJSONExtension returns true if the file extension indicates JSON format.
func isJSONExtension(path string) bool {
	return strings.ToLower(filepath.Ext(path)) == ".json"
}

// SHA256File computes the SHA256 checksum of a file and returns it as "sha256:<hex>".
func SHA256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}

	return "sha256:" + hex.EncodeToString(h.Sum(nil)), nil
}

// GenerateSchema returns a JSON Schema for the Manifest type.
func GenerateSchema() *jsonschema.Schema {
	reflector := jsonschema.Reflector{
		DoNotReference: true,
	}
	schema := reflector.Reflect(&Manifest{})
	schema.ID = jsonschema.ID(SchemaURL)
	schema.Title = "Boilerplate Manifest Schema"
	schema.Description = "Schema for boilerplate generation manifest"

	return schema
}

// GenerateSchemaJSON returns the canonical JSON encoding of the manifest schema.
// This is the authoritative output that the on-disk schema.json must match.
func GenerateSchemaJSON() ([]byte, error) {
	schema := GenerateSchema()

	var buf bytes.Buffer

	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)

	if err := enc.Encode(schema); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
