package manifest

import (
	"path/filepath"
)

// GeneratedFile represents a file that was generated by boilerplate
type GeneratedFile struct {
	Path string `json:"path"`
}

// Manifest represents the complete list of files generated by boilerplate
type Manifest struct {
	OutputDir string
	Files     []GeneratedFile
}

// NewManifest creates a new manifest
func NewManifest(outputDir string) *Manifest {
	return &Manifest{
		OutputDir: outputDir,
		Files:     []GeneratedFile{},
	}
}

// AddFile adds a generated file to the manifest
func (m *Manifest) AddFile(outputPath string) error {
	// Convert to relative path from output directory
	relPath, err := filepath.Rel(m.OutputDir, outputPath)
	if err != nil {
		relPath = outputPath
	}

	m.Files = append(m.Files, GeneratedFile{
		Path: relPath,
	})
	return nil
}
