name: CI

on:
  push:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  codespell:
    uses: ./.github/workflows/codespell.yml
    secrets: inherit

  markdownlint:
    uses: ./.github/workflows/markdownlint.yml
    secrets: inherit

  base_tests:
    needs: [lint, codespell, markdownlint]
    uses: ./.github/workflows/base-test.yml
    permissions:
      contents: read
      checks: write
    secrets: inherit

  build:
    needs: [lint, codespell, markdownlint]
    uses: ./.github/workflows/build.yml
    secrets: inherit

  integration_tests:
    needs: [base_tests, build]
    uses: ./.github/workflows/integration-test.yml
    permissions:
      contents: read
      checks: write
    secrets: inherit
